### ISSUE TITLE
Error when applying Bidirectional wrapper

### ISSUE THREAD

**Issue by XiYuan68** [titu1994/Keras-IndRNN#1]
tried: `Bidirectional(IndRNN(5, return_sequences=True), mode='sum')`

error occurs:

`Traceback (most recent call last):
 ......

  File "~/anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py", line 264, in __init__
    self.backward_layer = layer.__class__.from_config(config)

  File "ind_rnn.py", line 528, in from_config
    return cls(**config)

  File "~/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "ind_rnn.py", line 408, in __init__
    **kwargs)

  File "~/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py", line 380, in __init__
    super(RNN, self).__init__(**kwargs)

  File "~/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 293, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)

TypeError: ('Keyword argument not understood:', 'depth')
`

couldn't fix it myself, updates will be appreciated!!

**Comment by titu1994** [comment]
Fixed via 0283b50ff3efa5719a9d17d97cde42fa7f9eff61
