### ISSUE TITLE
Error when calling IndRNN with an initial state.

### ISSUE THREAD

**Issue by oscarberonius** [titu1994/Keras-IndRNN#6]
Hi, I am getting an error 

```
Traceback (most recent call last):
  File "lstm_seq2seq.py", line 145, in <module>
    initial_state=encoder_state)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/layers/recurrent.py", line 570, in __call__
    output = super(RNN, self).__call__(full_input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/ec2-user/test/keras/examples/ind_rnn.py", line 421, in build
    super(IndRNN, self).build(input_shape)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/layers/recurrent.py", line 493, in build
    self.cell.build(step_input_shape)
  File "/home/ec2-user/test/keras/examples/ind_rnn.py", line 141, in build
    self.recurrent_clip_max = pow(2.0, 1. / self.timesteps)
```

when trying to use the IndRNN instead of an LSTM for the example seq2seq implementation in the Keras source.

Here is the code that produces the error:

```
# Define an input sequence and process it.
encoder_inputs = Input(shape=(None, num_encoder_tokens))
encoder = IndRNN(latent_dim, return_state=True)
encoder_outputs, encoder_state = encoder(encoder_inputs)
# We discard 'encoder_outputs' and only keep the states.
# Set up the decoder, using 'encoder_state' as initial state.
decoder_inputs = Input(shape=(None, num_decoder_tokens))
# We set up our decoder to return full output sequences,
# and to return internal states as well. We don't use the
# return states in the training model, but we will use them in inference.
decoder_lstm = IndRNN(latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _ = decoder_lstm(decoder_inputs,
                                     initial_state=encoder_state)
decoder_dense = Dense(num_decoder_tokens, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)
```

Got any ideas why this happens?

Great job om in the implementation btw!

**Comment by titu1994** [comment]
IndRNN requires that the number of timesteps be provided properly, so that it can initializers the weights based on the number of timesteps. 

Therefore you cannot pass none as the number of timesteps in the input shape.

**Comment by mightoz** [comment]
I have tried using the correct input for the timesteps as well but am getting the same error. When you are ovverriding the build method of the base RNN class in Keras it seems like you didn't add a way to handle the input_shape that is passed when initial_state is used.
